### ISSUE TITLE
Release created incorrectly - needs to be deleted

### ISSUE THREAD

**Issue by famartinrh** [quarkiverse/quarkus-apicurio-registry-client#26]
hey @gastaldi , please could you delete the 0.0.2 release I just created https://github.com/quarkiverse/quarkus-apicurio-registry-client/releases/tag/0.0.2

That release is not valid, I created it manually instead of following the correct process (creating a PR modifiying the project.yaml)

**Comment by gastaldi** [comment]
NP, done. 

BTW You should be able to do that too.
